### ISSUE TITLE
Managed code script not loading

### ISSUE THREAD

**Issue by IanKirwan** [umautobots/GTAVisionExport#25]
@barcharcraz  Any clues?

```
[17:46:34] [DEBUG] Created script domain 'ScriptDomain_B5AB06DC' with v2.10.5.
[17:46:34] [DEBUG] Loading scripts from 'C:\Program Files\Rockstar Games\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_B5AB06DC' ...
[17:46:34] [INFO] Loading assembly 'AWSSDK.dll' ...
[17:46:34] [DEBUG] Found 0 script(s) in 'AWSSDK.dll'.
.
.
.
[17:46:34] [INFO] Loading assembly 'NativeUI.dll' ...
[17:46:34] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
.
.
.
[17:46:34] [INFO] Loading assembly 'VAutodrive.dll' ...
[17:46:34] [DEBUG] Found 6 script(s) in 'VAutodrive.dll'.
[17:46:34] [INFO] Loading assembly 'VCommonFunctions.dll' ...
[17:46:34] [DEBUG] Found 2 script(s) in 'VCommonFunctions.dll'.
[17:46:34] [INFO] Loading assembly 'YamlDotNet.dll' ...
[17:46:34] [DEBUG] Found 0 script(s) in 'YamlDotNet.dll'.
[17:46:34] [DEBUG] Starting 10 script(s) ...
[17:46:34] [DEBUG] Instantiating script 'GTAVisionExport.VisionExport' in script domain 'ScriptDomain_B5AB06DC' ...
[17:46:35] [ERROR] Failed to instantiate script 'GTAVisionExport.VisionExport' because constructor threw an exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.WriteAllText(String path, String contents)
   at GTAVisionExport.VisionExport..ctor() in D:\Workspace\vs\GTAVisionExport\managed\GTAVisionExport\VisionExport.cs:line 82
[17:46:35] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_B5AB06DC' ...
[17:46:35] [DEBUG] Started script 'NativeUI.BigMessageThread'.
.
.
.
[17:46:35] [DEBUG] Instantiating script 'Cyron43.GtaV.Common.PerFrameFunctions' in script domain 'ScriptDomain_B5AB06DC' ...
[17:46:35] [DEBUG] Started script 'Cyron43.GtaV.Common.PerFrameFunctions'.
```

GTAVisionExport.cs contains the constructor code:
```
            // loading ini file
            var parser = new FileIniDataParser();
            var location = AppDomain.CurrentDomain.BaseDirectory;
            var data = parser.ReadFile(Path.Combine(location, "GTAVision.ini"));

            //UINotify(ConfigurationManager.AppSettings["database_connection"]);
            dataPath = data["Snapshots"]["OutputDir"];
            logFilePath = data["Snapshots"]["LogFile"];

            System.IO.File.WriteAllText(logFilePath, "VisionExport constructor called.\n");
            if (!Directory.Exists(dataPath)) Directory.CreateDirectory(dataPath);
```
I'm no c# programmer so I'm assuming this is trying to get logFilePath and dataPath from GTAVision.ini but because that info is not in GTAVision.ini null values are passed to WriteAllText etc. I don't know what this info should look look but tried modifying GTAVision.ini to look like this:
```
[Database]
ConnectionString=Server=127.0.0.1;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
[Snapshots]
LogFile=D:\Snapshots
OutputDir=D:\Snapshots\Output
```
ScriptHookVDotNet2.log now reports:
```
[18:39:11] [ERROR] Failed to instantiate script 'GTAVisionExport.VisionExport' because constructor threw an exception:
System.UnauthorizedAccessException: Access to the path 'D:\Snapshots' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at GTAVisionExport.VisionExport..ctor() in D:\Workspace\vs\GTAVisionExport\managed\GTAVisionExport\VisionExport.cs:line 83
```
Please help.

**Comment by IanKirwan** [comment]
Modified GTAVision.ini to contain:
```
[Database]
ConnectionString=Server=127.0.0.1;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
[Snapshots]
LogFile=D:\Snapshots\LogFile.txt
OutputDir=D:\Snapshots\Output
```
Now scripts load OK. Still not connecting to database, but thats another issue.

**Comment by Magnetar99** [comment]
@IanKirwan were you able to solve the connection to database issue?
