### ISSUE TITLE
 Offset and length were out of bounds: ImageUtils.cs:line 41

### ISSUE THREAD

**Issue by IanKirwan** [umautobots/GTAVisionExport#32]
This occured approximately 4 hours into a capture run.

```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at BitMiracle.LibTiff.Classic.Internal.CodecWithPredictor.fpDiff(Byte[] buffer, Int32 offset, Int32 count)
   at BitMiracle.LibTiff.Classic.Internal.CodecWithPredictor.PredictorEncodeTile(Byte[] buffer, Int32 offset, Int32 count, Int16 plane)
   at BitMiracle.LibTiff.Classic.Tiff.WriteEncodedStrip(Int32 strip, Byte[] buffer, Int32 offset, Int32 count)
   at BitMiracle.LibTiff.Classic.Tiff.WriteEncodedStrip(Int32 strip, Byte[] buffer, Int32 count)
   at GTAVisionUtils.ImageUtils.WriteToTiff(Tiff t, Int32 width, Int32 height, List`1 colors, Byte[] depth, Byte[] stencil) in D:\Git\GTAVisionExport\managed\GTAVisionUtils\ImageUtils.cs:line 93
   at GTAVisionUtils.ImageUtils.UploadToArchive(ZipArchive archive, String name, Int32 w, Int32 h, List`1 colors, Byte[] depth, Byte[] stencil) in D:\Git\GTAVisionExport\managed\GTAVisionUtils\ImageUtils.cs:line 41
   at GTAVisionUtils.ImageUtils.<>c__DisplayClass4_0.<StartUploadTask>b__0() in D:\Git\GTAVisionExport\managed\GTAVisionUtils\ImageUtils.cs:line 33
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at GTAVisionUtils.ImageUtils.WaitForProcessing() in D:\Git\GTAVisionExport\managed\GTAVisionUtils\ImageUtils.cs:line 26
   at GTAVisionExport.VisionExport.OnTick(Object o, EventArgs e) in D:\Git\GTAVisionExport\managed\GTAVisionExport\VisionExport.cs:line 313
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
---> (Inner Exception #0) System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at BitMiracle.LibTiff.Classic.Internal.CodecWithPredictor.fpDiff(Byte[] buffer, Int32 offset, Int32 count)
   at BitMiracle.LibTiff.Classic.Internal.CodecWithPredictor.PredictorEncodeTile(Byte[] buffer, Int32 offset, Int32 count, Int16 plane)
   at BitMiracle.LibTiff.Classic.Tiff.WriteEncodedStrip(Int32 strip, Byte[] buffer, Int32 offset, Int32 count)
   at BitMiracle.LibTiff.Classic.Tiff.WriteEncodedStrip(Int32 strip, Byte[] buffer, Int32 count)
   at GTAVisionUtils.ImageUtils.WriteToTiff(Tiff t, Int32 width, Int32 height, List`1 colors, Byte[] depth, Byte[] stencil) in D:\Git\GTAVisionExport\managed\GTAVisionUtils\ImageUtils.cs:line 93
   at GTAVisionUtils.ImageUtils.UploadToArchive(ZipArchive archive, String name, Int32 w, Int32 h, List`1 colors, Byte[] depth, Byte[] stencil) in D:\Git\GTAVisionExport\managed\GTAVisionUtils\ImageUtils.cs:line 41
   at GTAVisionUtils.ImageUtils.<>c__DisplayClass4_0.<StartUploadTask>b__0() in D:\Git\GTAVisionExport\managed\GTAVisionUtils\ImageUtils.cs:line 33
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by gruberto** [comment]
I got a similar Exception when pressing the key "N" in order to capture an image.

[18:09:59] [DEBUG] Created script domain 'ScriptDomain_AD7D9324' with v2.10.6.
[18:09:59] [DEBUG] Loading scripts from 'D:\Software\GTA5\scripts' into script domain 'ScriptDomain_AD7D9324' ...
[18:09:59] [INFO] Loading assembly 'AWSSDK.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'AWSSDK.dll'.
[18:10:00] [INFO] Loading assembly 'BitMiracle.LibTiff.NET.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'BitMiracle.LibTiff.NET.dll'.
[18:10:00] [INFO] Loading assembly 'gdal_csharp.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'gdal_csharp.dll'.
[18:10:00] [INFO] Loading assembly 'GTAVisionExport.dll' ...
[18:10:00] [DEBUG] Found 1 script(s) in 'GTAVisionExport.dll'.
[18:10:00] [INFO] Loading assembly 'GTAVisionUtils.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'GTAVisionUtils.dll'.
[18:10:00] [INFO] Loading assembly 'INIFileParser.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'INIFileParser.dll'.
[18:10:00] [INFO] Loading assembly 'MathNet.Numerics.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'MathNet.Numerics.dll'.
[18:10:00] [INFO] Loading assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'.
[18:10:00] [INFO] Loading assembly 'Microsoft.Extensions.Logging.Abstractions.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'Microsoft.Extensions.Logging.Abstractions.dll'.
[18:10:00] [INFO] Loading assembly 'Microsoft.Extensions.Logging.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'Microsoft.Extensions.Logging.dll'.
[18:10:00] [INFO] Loading assembly 'NativeUI.dll' ...
[18:10:00] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[18:10:00] [INFO] Loading assembly 'Npgsql.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'Npgsql.dll'.
[18:10:00] [INFO] Loading assembly 'ogr_csharp.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'ogr_csharp.dll'.
[18:10:00] [INFO] Loading assembly 'osr_csharp.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'osr_csharp.dll'.
[18:10:00] [INFO] Loading assembly 'SharpDX.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'SharpDX.dll'.
[18:10:00] [INFO] Loading assembly 'SharpDX.Mathematics.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'SharpDX.Mathematics.dll'.
[18:10:00] [INFO] Loading assembly 'System.Runtime.InteropServices.RuntimeInformation.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'System.Runtime.InteropServices.RuntimeInformation.dll'.
[18:10:00] [INFO] Loading assembly 'System.Threading.Tasks.Extensions.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'System.Threading.Tasks.Extensions.dll'.
[18:10:00] [INFO] Loading assembly 'VAutodrive.dll' ...
[18:10:00] [DEBUG] Found 6 script(s) in 'VAutodrive.dll'.
[18:10:00] [INFO] Loading assembly 'VCommonFunctions.dll' ...
[18:10:00] [DEBUG] Found 2 script(s) in 'VCommonFunctions.dll'.
[18:10:00] [INFO] Loading assembly 'YamlDotNet.dll' ...
[18:10:00] [DEBUG] Found 0 script(s) in 'YamlDotNet.dll'.
[18:10:00] [DEBUG] Starting 10 script(s) ...
[18:10:00] [DEBUG] Instantiating script 'GTAVisionExport.VisionExport' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'GTAVisionExport.VisionExport'.
[18:10:01] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[18:10:01] [DEBUG] Instantiating script 'VAutodrive.VehicleMoversHandling' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'VAutodrive.VehicleMoversHandling'.
[18:10:01] [DEBUG] Instantiating script 'VAutodrive.MenuHandling' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'VAutodrive.MenuHandling'.
[18:10:01] [DEBUG] Instantiating script 'VAutodrive.KeyHandling' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'VAutodrive.KeyHandling'.
[18:10:01] [DEBUG] Instantiating script 'VAutodrive.Autopilot' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'VAutodrive.Autopilot'.
[18:10:01] [DEBUG] Instantiating script 'VAutodrive.SeatHandling' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'VAutodrive.SeatHandling'.
[18:10:01] [DEBUG] Instantiating script 'VAutodrive.WalkHandling' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'VAutodrive.WalkHandling'.
[18:10:01] [DEBUG] Instantiating script 'Cyron43.GtaV.Common.NotificationTask' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'Cyron43.GtaV.Common.NotificationTask'.
[18:10:01] [DEBUG] Instantiating script 'Cyron43.GtaV.Common.PerFrameFunctions' in script domain 'ScriptDomain_AD7D9324' ...
[18:10:01] [DEBUG] Started script 'Cyron43.GtaV.Common.PerFrameFunctions'.
[18:16:09] [ERROR] Caught unhandled exception:
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at BitMiracle.LibTiff.Classic.Internal.CodecWithPredictor.fpDiff(Byte[] buffer, Int32 offset, Int32 count)
   at BitMiracle.LibTiff.Classic.Internal.CodecWithPredictor.PredictorEncodeTile(Byte[] buffer, Int32 offset, Int32 count, Int16 plane)
   at BitMiracle.LibTiff.Classic.Tiff.WriteEncodedStrip(Int32 strip, Byte[] buffer, Int32 offset, Int32 count)
   at GTAVisionUtils.ImageUtils.WriteToTiff(Tiff t, Int32 width, Int32 height, List`1 colors, Byte[] depth, Byte[] stencil) in D:\Software\GTAVisionExport\managed\GTAVisionUtils\ImageUtils.cs:line 94
   at GTAVisionExport.VisionExport.OnKeyDown(Object o, KeyEventArgs k) in D:\Software\GTAVisionExport\managed\GTAVisionExport\VisionExport.cs:line 652
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()

Can you help me? Thanks!
